services:
  - type: web
    name: rice-disease-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health 